hc/urls.py
from __future__ import annotations

from django.contrib import admin
from django.urls import include, path

from hc.accounts import views as accounts_views

urlpatterns = [
    path("admin/login/", accounts_views.login),
    path("admin/", admin.site.urls),
    path("accounts/", include("hc.accounts.urls")),
    path("projects/add/", accounts_views.add_project, name="hc-add-project"),
    path(
        "projects/<uuid:code>/settings/",
        accounts_views.project,
        name="hc-project-settings",
    ),
    path(
        "projects/<uuid:code>/remove/",
        accounts_views.remove_project,
        name="hc-remove-project",
    ),
    path("", include("hc.api.urls")),
    path("", include("hc.front.urls")),
    path("", include("hc.payments.urls")),
]

hc/front/forms.py
from __future__ import annotations

import json
import re
from datetime import datetime
from datetime import timedelta as td
from datetime import timezone
from urllib.parse import quote, urlencode

from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.forms import URLField

from hc.front.validators import (
    CronExpressionValidator,
    TimezoneValidator,
    WebhookValidator,
)
from hc.lib import curl


def _is_latin1(s):
    try:
        s.encode("latin-1")
        return True
    except UnicodeError:
        return False


class HeadersField(forms.Field):
    message = """Use "Header-Name: value" pairs, one per line."""

    def to_python(self, value):
        if not value:
            return {}

        headers = {}
        for line in value.split("\n"):
            if not line.strip():
                continue

            if ":" not in line:
                raise ValidationError(self.message)

            n, v = line.split(":", maxsplit=1)
            n, v = n.strip(), v.strip()
            if not n or not v:
                raise ValidationError(message=self.message)

            if not _is_latin1(n):
                raise ValidationError(
                    message="Header names must not contain special characters"
                )

            headers[n] = v

        return headers

    def validate(self, value):
        super().validate(value)
        for k, v in value.items():
            if len(k) > 1000 or len(v) > 1000:
                raise ValidationError("Value too long")


class NameTagsForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)
    tags = forms.CharField(max_length=500, required=False)
    desc = forms.CharField(required=False)

    def clean_tags(self):
        result = []

        for part in self.cleaned_data["tags"].split(" "):
            part = part.strip()
            if part != "":
                result.append(part)

        return " ".join(result)


class AddCheckForm(NameTagsForm):
    kind = forms.ChoiceField(choices=(("simple", "simple"), ("cron", "cron")))
    timeout = forms.IntegerField(min_value=60, max_value=31536000)
    schedule = forms.CharField(max_length=100, validators=[CronExpressionValidator()])
    tz = forms.CharField(max_length=36, validators=[TimezoneValidator()])
    grace = forms.IntegerField(min_value=60, max_value=31536000)

    def clean_timeout(self):
        return td(seconds=self.cleaned_data["timeout"])

    def clean_grace(self):
        return td(seconds=self.cleaned_data["grace"])


class FilteringRulesForm(forms.Form):
    filter_subject = forms.BooleanField(required=False)
    filter_body = forms.BooleanField(required=False)
    success_kw = forms.CharField(required=False, max_length=200)
    failure_kw = forms.CharField(required=False, max_length=200)
    methods = forms.ChoiceField(required=False, choices=(("", "Any"), ("POST", "POST")))
    manual_resume = forms.BooleanField(required=False)


class TimeoutForm(forms.Form):
    timeout = forms.IntegerField(min_value=60, max_value=31536000)
    grace = forms.IntegerField(min_value=60, max_value=31536000)

    def clean_timeout(self):
        return td(seconds=self.cleaned_data["timeout"])

    def clean_grace(self):
        return td(seconds=self.cleaned_data["grace"])


class CronForm(forms.Form):
    schedule = forms.CharField(max_length=100, validators=[CronExpressionValidator()])
    tz = forms.CharField(max_length=36, validators=[TimezoneValidator()])
    grace = forms.IntegerField(min_value=1, max_value=43200)


class AddOpsgenieForm(forms.Form):
    error_css_class = "has-error"
    region = forms.ChoiceField(initial="us", choices=(("us", "US"), ("eu", "EU")))
    key = forms.CharField(max_length=40)


class AddPushoverForm(forms.Form):
    error_css_class = "has-error"
    pushover_user_key = forms.CharField()
    prio = forms.IntegerField(initial=0, min_value=-3, max_value=2)
    prio_up = forms.IntegerField(initial=0, min_value=-3, max_value=2)

    def get_value(self):
        key = self.cleaned_data["pushover_user_key"]
        prio = self.cleaned_data["prio"]
        prio_up = self.cleaned_data["prio_up"]
        return "%s|%s|%s" % (key, prio, prio_up)


class EmailForm(forms.Form):
    error_css_class = "has-error"
    value = forms.EmailField(max_length=100)
    down = forms.BooleanField(required=False, initial=True)
    up = forms.BooleanField(required=False, initial=True)

    def clean(self):
        super().clean()

        down = self.cleaned_data.get("down")
        up = self.cleaned_data.get("up")

        if not down and not up:
            self.add_error("down", "Please select at least one.")

    def get_value(self):
        return json.dumps(dict(self.cleaned_data), sort_keys=True)


class AddUrlForm(forms.Form):
    error_css_class = "has-error"
    value = forms.URLField(max_length=1000, validators=[WebhookValidator()])


METHODS = ("GET", "POST", "PUT")


class WebhookForm(forms.Form):
    error_css_class = "has-error"
    name = forms.CharField(max_length=100, required=False)

    method_down = forms.ChoiceField(initial="GET", choices=zip(METHODS, METHODS))
    body_down = forms.CharField(max_length=1000, required=False)
    headers_down = HeadersField(required=False)
    url_down = URLField(
        max_length=1000, required=False, validators=[WebhookValidator()]
    )

    method_up = forms.ChoiceField(initial="GET", choices=zip(METHODS, METHODS))
    body_up = forms.CharField(max_length=1000, required=False)
    headers_up = HeadersField(required=False)
    url_up = forms.URLField(
        max_length=1000, required=False, validators=[WebhookValidator()]
    )

    def clean(self):
        super().clean()

        url_down = self.cleaned_data.get("url_down")
        url_up = self.cleaned_data.get("url_up")

        if not url_down and not url_up:
            if not self.has_error("url_down"):
                self.add_error("url_down", "Enter a valid URL.")

    def get_value(self):
        return json.dumps(dict(self.cleaned_data), sort_keys=True)


class AddShellForm(forms.Form):
    error_css_class = "has-error"

    cmd_down = forms.CharField(max_length=1000, required=False)
    cmd_up = forms.CharField(max_length=1000, required=False)

    def get_value(self):
        return json.dumps(dict(self.cleaned_data), sort_keys=True)


class PhoneNumberForm(forms.Form):
    error_css_class = "has-error"
    label = forms.CharField(max_length=100, required=False)
    phone = forms.CharField()

    def clean_phone(self):
        v = self.cleaned_data["phone"]

        stripped = v.encode("ascii", "ignore").decode("ascii")
        stripped = stripped.replace(" ", "").replace("-", "")
        if not re.match(r"^\+\d{5,15}$", stripped):
            raise forms.ValidationError("Invalid phone number format.")

        return stripped

    def get_json(self):
        return json.dumps({"value": self.cleaned_data["phone"]})


class PhoneUpDownForm(PhoneNumberForm):
    up = forms.BooleanField(required=False, initial=True)
    down = forms.BooleanField(required=False, initial=True)

    def clean(self):
        super().clean()

        down = self.cleaned_data.get("down")
        up = self.cleaned_data.get("up")

        if not down and not up:
            self.add_error("down", "Please select at least one.")

    def get_json(self):
        return json.dumps(
            {
                "value": self.cleaned_data["phone"],
                "up": self.cleaned_data["up"],
                "down": self.cleaned_data["down"],
            }
        )


class ChannelNameForm(forms.Form):
    name = forms.CharField(max_length=100, required=False)


class AddMatrixForm(forms.Form):
    error_css_class = "has-error"
    alias = forms.CharField(max_length=100)

    def clean_alias(self):
        v = self.cleaned_data["alias"]

        # validate it by trying to join
        url = settings.MATRIX_HOMESERVER
        url += "/_matrix/client/r0/join/%s?" % quote(v)
        url += urlencode({"access_token": settings.MATRIX_ACCESS_TOKEN})
        r = curl.post(url, {})
        if r.status_code == 429:
            raise forms.ValidationError(
                "Matrix server returned status code 429 (Too Many Requests), "
                "please try again later."
            )
        if r.status_code == 502:
            raise forms.ValidationError(
                "Matrix server returned status code 502 (Bad Gateway), "
                "please try again later."
            )

        doc = r.json()
        if "error" in doc:
            raise forms.ValidationError("Response from Matrix: %s" % doc["error"])

        self.cleaned_data["room_id"] = doc["room_id"]

        return v


class AddAppriseForm(forms.Form):
    error_css_class = "has-error"
    url = forms.CharField(max_length=512)


class AddPdForm(forms.Form):
    error_css_class = "has-error"
    value = forms.CharField(max_length=32)


ZULIP_TARGETS = (("stream", "Stream"), ("private", "Private"))


class AddZulipForm(forms.Form):
    error_css_class = "has-error"
    bot_email = forms.EmailField(max_length=100)
    api_key = forms.CharField(max_length=50)
    site = forms.URLField(max_length=100, validators=[WebhookValidator()])
    mtype = forms.ChoiceField(choices=ZULIP_TARGETS)
    to = forms.CharField(max_length=100)
    topic = forms.CharField(max_length=100, required=False)

    def get_value(self):
        return json.dumps(dict(self.cleaned_data), sort_keys=True)


class AddTrelloForm(forms.Form):
    token = forms.RegexField(regex=r"^[0-9a-fA-F]{64}$")
    board_name = forms.CharField(max_length=100)
    list_name = forms.CharField(max_length=100)
    list_id = forms.RegexField(regex=r"^[0-9a-fA-F]{16,32}$")

    def get_value(self):
        return json.dumps(dict(self.cleaned_data), sort_keys=True)


class AddGotifyForm(forms.Form):
    error_css_class = "has-error"
    token = forms.CharField(max_length=50)

templates/integrations/add_discord.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Discord Integration for {{ site_name }}{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>Discord</h1>

    <div class="jumbotron">
        <p>
            With this integration, {{ site_name }} will send
            a notification to a <a href="http://discord.com/">Discord</a>
            channel when a check
            goes <strong>up</strong> or <strong>down</strong>.
        </p>

        <form method="post" class="text-center">
            {% csrf_token %}
            <a href="{{ authorize_url }}" class="btn btn-lg btn-default">
                <img class="ai-icon" src="{% static 'img/integrations/discord.png' %}" alt="Discord" />
                Connect Discord
            </a>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/integrations/add_mattermost.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}Mattermost Integration for {{ site_name }}{% endblock %}
{% block description %}
    <meta name="description" content="If your team uses Mattermost, you can set up {{ site_name }} to post alerts directly to an appropriate Mattermost channel when a check goes up or down.">
{% endblock %}

{% block content %}
<div class="row">
<div class="col-sm-12">

    <h1>Mattermost</h1>
    <div class="jumbotron">
        {% if request.user.is_authenticated %}
        <p>
            If your team uses <a href="https://mattermost.com/">Mattermost</a>,
            you can set up {{ site_name }} to post alerts directly to an
            appropriate Mattermost channel when a check goes <strong>up</strong>
            or <strong>down</strong>.
        </p>
        {% else %}
        <p>
            {{ site_name }} is a free and
            <a href="https://github.com/healthchecks/healthchecks">open source</a>
            service for monitoring <strong>cron jobs</strong>, <strong>background processes</strong> and
            <strong>scheduled tasks</strong>. When {% site_name %} detects a problem, it can notify
            you by posting to a Mattermost channel. To set up the Mattermost
            integration, please sign into {{ site_name }}:
        </p>

        <div class="text-center">
            <a href="{% url 'hc-login' %}"
               class="btn btn-primary btn-lg">Sign In</a>
        </div>
        {% endif %}
    </div>

    <h2>Setup Guide</h2>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            Log into your Mattermost account and
            select <strong>Integrations</strong> in the
            top left menu.
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_mattermost_1.png' %}">
        </div>
    </div>
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            <p>
            In the "Integrations" screen, select <strong>Incoming Webhook</strong>
            and then <strong>Add Incoming Webhook</strong>.
            </p>
            <p>Fill in the form and hit "Save".</p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_mattermost_2.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            {% if project %}
            <p>Copy the displayed <strong>URL</strong> and paste it in the form below.</p>
            <p>Save the integration, and you are all set!</p>
            {% else %}
            <p>Copy the displayed <strong>URL</strong>.</p>
            {% endif %}
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_mattermost_3.png' %}">
        </div>
    </div>

    {% if not project %}
    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            <p>Sign into {% site_name %}, then go to the <strong>Integrations</strong>
                page and click on <strong>Add Integration</strong> next to the
                Mattermost integration.
            </p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_mattermost_4.png' %}">
        </div>
    </div>

    <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            <p>Paste the copied <strong>URL</strong> in the form.</p>
            <p>Save the integration, and you are all set!</p>
        </div>
        <div class="col-sm-6">
            <img
                class="ai-guide-screenshot"
                alt="Screenshot"
                src="{% static 'img/integrations/setup_mattermost_5.png' %}">
        </div>
    </div>
    {% endif %}

    {% if project %}
    <h2>Integration Settings</h2>
    <form method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group {{ form.value.css_classes }}">
            <label for="callback-url" class="col-sm-2 control-label">
                Webhook URL
            </label>
            <div class="col-sm-10">
                <input
                    id="callback-url"
                    type="text"
                    class="form-control"
                    name="value"
                    placeholder="https://"
                    value="{{ form.value.value|default:"" }}">

                {% if form.value.errors %}
                <div class="help-block">
                    {{ form.value.errors|join:"" }}
                </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save Integration</button>
            </div>
        </div>
    </form>
    {% endif %}
</div>
</div>
{% endblock %}

templates/integrations/add_pagertree.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}PagerTree Integration for {{ site_name }}{% endblock %}


{% block content %}
<div class="row">
  <div class="col-sm-12">
      <h1>PagerTree</h1>

      <p>If your team uses <a href="https://pagertree.com">PagerTree</a>,
      you can set up {{ site_name }} to create a PagerTree alert when
      a check goes down, and resolve it when a check goes back up.</p>

      <h2>Setup Guide</h2>

      <div class="row ai-step">
        <div class="col-sm-6">
            <span class="step-no"></span>
            <p>
                Log into your PagerTree account, navigate to the <a href="https://app.pagertree.com/integrations?direction=asc&limit=10&sort=tiny_id" target="_blank">Integrations page</a>.
                Then click the <strong>New Integration</strong> button and
                select the <strong>Healthchecks</strong> logo.
            </p>
        </div>
        <div class="col-sm-6">
            <div class="marker-wrap">
                <span style="left: 89%; top: 35%;" class="marker"></span>
                <img
                    class="ai-guide-screenshot"
                    alt="Click create integration button"
                    src="{% static 'img/integrations/setup_pagertree_1.png' %}" />
            </div>
        </div>
      </div>

      <div class="row ai-step">
          <div class="col-sm-6">
              <span class="step-no"></span>
              <p>
                  In the New Integration Form, fill out the details with appropriate values. Then click the <strong>Create</strong> button.
              </p>
          </div>
          <div class="col-sm-6">
              <img
                  class="ai-guide-screenshot"
                  alt="Create Healthchecks.io integration with details"
                  src="{% static 'img/integrations/setup_pagertree_2.png' %}">
          </div>
      </div>

      <div class="row ai-step">
          <div class="col-sm-6">
              <span class="step-no"></span>
              <p>
                Copy the <strong>Endpoint URL</strong> and paste it
                in the form below.
                Save the integration, and you are done!
              </p>
          </div>
          <div class="col-sm-6">
            <div class="marker-wrap">
                <span style="left: 48.5%; top: 87%;" class="marker"></span>

                  <img
                      class="ai-guide-screenshot"
                      alt="Copy the Webhook URL"
                      src="{% static 'img/integrations/setup_pagertree_3.png' %}">
            </div>
          </div>
      </div>

      <h2>Integration Settings</h2>

      <form method="post" class="form-horizontal">
          {% csrf_token %}
          <div class="form-group {{ form.value.css_classes }}">
              <label for="post-url" class="col-sm-2 control-label">Endpoint</label>
              <div class="col-sm-10">
                  <input
                      id="post-url"
                      type="text"
                      class="form-control"
                      name="value"
                      placeholder="https://"
                      value="{{ form.value.value|default:"" }}">

                  {% if form.value.errors %}
                  <div class="help-block">
                      {{ form.value.errors|join:"" }}
                  </div>
                  {% endif %}
              </div>
          </div>
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                  <button type="submit" class="btn btn-primary">Save Integration</button>
              </div>
          </div>
      </form>
  </div>
</div>
{% endblock %}

templates/integrations/apprise_description.html
{% load humanize %}
{{ check.name_then_code }} is {{ check.status|upper }}.
{% if check.status == "down" %}
Last ping was {{ check.last_ping|naturaltime }}.
{% endif %}

templates/integrations/matrix_description.html
{% load humanize %}
{% if check.status == "down" %}
    {{ check.name_then_code }} is DOWN. Last ping was {{ check.last_ping|naturaltime }}.
{% else %}
    {{ check.name_then_code }} is now UP.
{% endif %}

templates/integrations/pagertree_description.html
{% load humanize %}
{{ check.name_then_code }} is {{ check.status|upper }}.
{% if check.status == "down" %}
Last ping was {{ check.last_ping|naturaltime }}.
{% endif %}

templates/integrations/pagertree_title.html
{{ check.name_then_code|safe }} is {{ check.status|upper }}

templates/integrations/pd_description.html
{% if check.status == "down" %}
    {{ check.name_then_code|safe }} is DOWN
{% else %}
    {{ check.name_then_code|safe }} received a ping and is now UP
{% endif %}

templates/integrations/pushbullet_message.html
{% load humanize %}

{% if check.status == "down" %}
The check "{{ check.name_then_code|safe }}" is DOWN. Last ping was {{ check.last_ping|naturaltime }}
{% else %}
The check "{{ check.name_then_code|safe }}" received a ping and is now UP.
{% endif %}

templates/integrations/signal_form.html
{% extends "base.html" %}
{% load compress humanize static hc_extras %}

{% block title %}
{% if is_new %}
Add Signal Integration - {% site_name %}
{% else %}
Signal Settings - {% site_name %}
{% endif %}
{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>Signal</h1>

    <p>Get a Signal message when a check goes up or down.</p>

    <h2>Integration Settings</h2>

    <form method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group {{ form.label.css_classes }}">
            <label for="id_label" class="col-sm-2 control-label">Label</label>
            <div class="col-sm-6">
                <input
                    id="id_label"
                    type="text"
                    class="form-control"
                    name="label"
                    placeholder="Alice's Phone"
                    value="{{ form.label.value|default:"" }}">

                {% if form.label.errors %}
                <div class="help-block">
                    {{ form.label.errors|join:"" }}
                </div>
                {% else %}
                <span class="help-block">
                    Optional. If you add multiple phone numbers,
                    the labels will help you tell them apart.
                </span>
                {% endif %}
            </div>
        </div>

        <div class="form-group {{ form.phone.css_classes }}">
            <label for="id_number" class="col-sm-2 control-label">Phone Number</label>
            <div class="col-sm-6">
                <div class="input-group">
                    <input
                        id="id_number"
                        type="tel"
                        class="form-control"
                        name="phone"
                        placeholder="+1234567890"
                        value="{{ form.phone.value|default:"" }}">

                    <span class="input-group-btn">
                        <button
                            id="signal-verify-btn"
                            type="button"
                            class="btn btn-default"
                            data-verify-url="{% url 'hc-signal-verify' %}">
                            <span>Send Test Message!</span>
                            <div class="spinner"></div>
                        </button>
                    </span>
                </div>

                {% if form.phone.errors %}
                <div class="help-block">
                    {{ form.phone.errors|join:"" }}
                </div>
                {% else %}
                <span class="help-block">
                    Make sure the phone number starts with "+" and  has the
                    country code.
                </span>
                {% endif %}

                <div id="verify-result"></div>
            </div>
        </div>

        <div class="form-group {{ form.down.css_classes }}">
            <label class="col-sm-2 control-label">Notify When</label>
            <div class="col-sm-10">
                <label class="checkbox-container">
                    <input
                        type="checkbox"
                        name="down"
                        value="true"
                        {% if form.down.value %} checked {% endif %}>
                    <span class="checkmark"></span>
                    A check goes <strong>down</strong>
                </label>
                <label class="checkbox-container">
                    <input
                        type="checkbox"
                        name="up"
                        value="true"
                        {% if form.up.value %} checked {% endif %}>
                    <span class="checkmark"></span>
                    A check goes <strong>up</strong>
                    {% if form.down.errors %}
                    <div class="help-block">
                        {{ form.down.errors|join:"" }}
                    </div>
                    {% endif %}
                </label>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button
                    id="submit-btn"
                    type="submit"
                    class="btn btn-primary"
                    title="Please verify the number by sending a test message first."
                    disabled>Save Integration</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    {% compress js %}
    <script src="{% static 'js/signal_form.js' %}"></script>
    {% endcompress %}
{% endblock %}

templates/integrations/sms_form.html
{% extends "base.html" %}
{% load humanize static hc_extras %}

{% block title %}
{% if is_new %}
Add SMS Integration - {% site_name %}
{% else %}
SMS Settings - {% site_name %}
{% endif %}
{% endblock %}


{% block content %}
<div class="row">
<div class="col-sm-12">
    <h1>SMS</h1>

    <p>
        Get a SMS message to the specified phone number when a
        check goes down.
    </p>

    {% if show_pricing and profile.sms_limit == 0 %}
    <p class="alert alert-info">
        <strong>Paid plan required.</strong>
        SMS messaging is not available on the free plan–sending the messages
        cost too much! Please upgrade to a
        <a href="{% url 'hc-billing' %}">paid plan</a> to enable SMS messaging.
    </p>
    {% endif %}

    <h2>Integration Settings</h2>

    <form method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group {{ form.label.css_classes }}">
            <label for="id_label" class="col-sm-2 control-label">Label</label>
            <div class="col-sm-6">
                <input
                    id="id_label"
                    type="text"
                    class="form-control"
                    name="label"
                    placeholder="Alice's Phone"
                    value="{{ form.label.value|default:"" }}">

                {% if form.label.errors %}
                <div class="help-block">
                    {{ form.label.errors|join:"" }}
                </div>
                {% else %}
                <span class="help-block">
                    Optional. If you add multiple phone numbers,
                    the labels will help you tell them apart.
                </span>
                {% endif %}
            </div>
        </div>
        <div class="form-group {{ form.phone.css_classes }}">
            <label for="id_number" class="col-sm-2 control-label">Phone Number</label>
            <div class="col-sm-3">
                <input
                    id="id_number"
                    type="tel"
                    class="form-control"
                    name="phone"
                    placeholder="+1234567890"
                    value="{{ form.phone.value|default:"" }}">

                {% if form.phone.errors %}
                <div class="help-block">
                    {{ form.phone.errors|join:"" }}
                </div>
                {% else %}
                <span class="help-block">
                    Make sure the phone number starts with "+" and  has the
                    country code.
                </span>
                {% endif %}
            </div>
        </div>
        <div class="form-group {{ form.down.css_classes }}">
            <label class="col-sm-2 control-label">Notify When</label>
            <div class="col-sm-10">
                <label class="checkbox-container">
                    <input
                        type="checkbox"
                        name="down"
                        value="true"
                        {% if form.down.value %} checked {% endif %}>
                    <span class="checkmark"></span>
                    A check goes <strong>down</strong>
                </label>
                <label class="checkbox-container">
                    <input
                        type="checkbox"
                        name="up"
                        value="true"
                        {% if form.up.value %} checked {% endif %}>
                    <span class="checkmark"></span>
                    A check goes <strong>up</strong>
                    {% if form.down.errors %}
                    <div class="help-block">
                        {{ form.down.errors|join:"" }}
                    </div>
                    {% endif %}
                </label>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Save Integration</button>
            </div>
        </div>
    </form>
</div>
</div>
{% endblock %}